### PR TITLE
ONVIF Discovery Handler - Handle Multicast Response Duplicates

### LINKED ISSUE #365: Remove duplicates after discovering ONVIF cameras.
**Describe the bug**
Akri discovers cameras by doing a multicast for a configurable amount of seconds. Then, it filters all the responses by scopes and then calls `GetSystemDateAndTime` on the remaining cameras. This call should only be made once per camera; however, it appears that cameras are being discovered multiple times in the multicast and then being pinged for aliveness multiple times:
`2021-08-25T13:29:25Z TRACE akri_onvif::discovery_impl::util] simple_onvif_discover - uris after filtering by scopes ["http://10.111.222.251/onvif/device_service", "http://10.234.123.456:80/wsd/mex", "http://10.234.123.456:80/wsd/mex"]`
The vector of multicast responses should be deduped before proceeding with the next steps.

**Flow**
Installation command:
```
helm install akri akri-helm-charts/akri \
    --set onvif.discovery.enabled=true \
    --set onvif.configuration.enabled=true
```
ONVIF Discovery Handler log snippet:
```
2021-08-25T13:29:25Z TRACE akri_onvif::discovery_impl::util] simple_onvif_discover - uris after filtering by scopes ["http://10.111.222.251/onvif/device_service", "http://10.234.123.456:80/wsd/mex", "http://10.234.123.456:80/wsd/mex"]
[2021-08-25T13:29:25Z TRACE akri_onvif::discovery_utils] post - url:http://10.111.222.251/onvif/device_service, mime_action:action="http://www.onvif.org/ver10/device/wsdl/GetSystemDateAndTime", msg:<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsdl="http://www.onvif.org/ver10/device/wsdl">
        <soap:Header/>
            <soap:Body>
                <wsdl:GetSystemDateAndTime/>
            </soap:Body>
        </soap:Envelope>
[2021-08-25T13:29:25Z TRACE akri_onvif::discovery_utils] post - url:http://10.234.123.456:80/wsd/mex, mime_action:action="http://www.onvif.org/ver10/device/wsdl/GetSystemDateAndTime", msg:<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsdl="http://www.onvif.org/ver10/device/wsdl">
        <soap:Header/>
            <soap:Body>
                <wsdl:GetSystemDateAndTime/>
            </soap:Body>
        </soap:Envelope>
[2021-08-25T13:29:25Z TRACE akri_onvif::discovery_utils] post - url:http://10.234.123.456:80/wsd/mex, mime_action:action="http://www.onvif.org/ver10/device/wsdl/GetSystemDateAndTime", msg:<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsdl="http://www.onvif.org/ver10/device/wsdl">
        <soap:Header/>
            <soap:Body>
                <wsdl:GetSystemDateAndTime/>
            </soap:Body>
        </soap:Envelope>
```

**Proposed fix**
Remove duplicates from `filtered_uris` before passing them into `get_responsive_uris` [here](https://github.com/deislabs/akri/blob/main/discovery-handlers/onvif/src/discovery_impl.rs#L355)

### PR DESCRIPTION
**Pull request by kate-goldenring**
**What this PR does / why we need it**:
closes #365 

**Special notes for your reviewer**:
Seems like our multicast occasionally returns the same service url twice. Simply deduping the returned ONVIF service URLs seems like a good strategy.

**If applicable**:
- [ ] this PR has an associated PR with documentation in [akri-docs](https://github.com/deislabs/akri-docs)
- [ ] this PR contains unit tests
- [x] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [x] code is free of common mistakes (`cargo clippy`)
- [x] all Akri tests succeed (`cargo test`)
- [ ] inline documentation builds (`cargo doc`)
- [x] version has been updated appropriately (`./version.sh`)

### CODE REVIEW

File: discovery-handlers/onvif/src/discovery_impl.rs [hunk 1]
```diff
@@ -352,6 +352,7 @@ pub mod util {
             "simple_onvif_discover - uris after filtering by scopes {:?}",
             filtered_uris
         );
+        filtered_uris.dedup();
```
Comment (jiria) [inline discovery-handlers/onvif/src/discovery_impl.rs:355]: Would it make sense to have broadcast_responses to be a set so that we do not capture duplicates in the first place or dedup on broadcast_responses prior to calling get_scope_filtered_uris_from_discovery_response?

**Comment by romoh** [comment]
Curious, do we understand why duplicates happen in the first place?
I wonder if this is a side effect for another bug and we are only solving the symptom here.

**Comment by kate-goldenring** [comment]
> Curious, do we understand why duplicates happen in the first place?
> I wonder if this is a side effect for another bug and we are only solving the symptom here.

Might be. Have no way of telling until we run into it or get the logs.

File: discovery-handlers/onvif/src/discovery_impl.rs (hunk 1 above)
Comment (kate-goldenring) [reply discovery-handlers/onvif/src/discovery_impl.rs]: Good point! Switched to a hashset in 80bcc3b8295272

**Comment by romoh** [comment]
> > Curious, do we understand why duplicates happen in the first place?
> > I wonder if this is a side effect for another bug and we are only solving the symptom here.
> 
> Might be. Have no way of telling until we run into it or get the logs.

Fair. Maybe it is worth adding a note in the bug and making sure we have enough logging in place to be able to root cause this if it happens again.

**Review by romoh — APPROVED** [review]

File: discovery-handlers/onvif/src/discovery_impl.rs [hunk 2]
```diff
@@ -323,7 +323,7 @@ pub mod util {
 
             match try_recv_string(socket, time_left).await {
                 Ok(s) => {
-                    broadcast_responses.push(s);
+                    broadcast_responses.insert(s);
```
Comment (bfjelds) [inline discovery-handlers/onvif/src/discovery_impl.rs:326]: i wonder if we might want to s.ToLower here (i assume that a device would be consistent in how it describes itself, so it seems like this wouldn't be needed ... but something to think about)

**Review by bfjelds — APPROVED** [review]
