### PR TITLE
Expand udev rule support

### LINKED ISSUE #114: Akri udev ATTRS ignored
**Describe the bug**
Based on the Akri [udev grammar](https://github.com/deislabs/akri/blob/main/agent/src/protocols/udev/udev_rule_grammar.pest) it seems that ATTRS might be supported, but when I pass ATTRS as part of my udev rule, Agent is ignoring it:
```
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_impl] parse_udev_rule - unsupported field ATTRS{manufacturer}
```
Is v2 not yet supported?

**Output of `kubectl get pods,akrii,akric -o wide`**
agent and controller are running, my configuration is specified, but too many instances are found, because ATTRS of the rule are ignored

**Kubernetes Version: K3s**

**To Reproduce**
Supplying rule such as `SUBSYSTEM=="tty"\, ATTRS{manufacturer}=="Silicon Labs"\, ATTRS{idProduct}=="ea60"'` matches all tty devices.

**Expected behavior**
Supplying rule such as `SUBSYSTEM=="tty"\, ATTRS{manufacturer}=="Silicon Labs"\, ATTRS{idProduct}=="ea60"'` should only match tty devices that have manufacturer and idProduct in the device or its parents.

**Logs (please share snips of applicable logs)**
Snippet from Agent log:
```
[2020-11-08T09:04:14Z TRACE agent::util::config_action] do_periodic_discovery - start for config akri-udev
[2020-11-08T09:04:14Z TRACE agent::util::config_action] do_periodic_discovery - loop iteration for config akri-udev
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_handler] discover - for udev rules ["SUBSYSTEM==\"tty\", ATTRS{manufacturer}==\"Silicon Labs\", ATTRS{idProduct}
==\"ea60\""]
[2020-11-08T09:04:14Z INFO  agent::protocols::udev::discovery_impl] parse_udev_rule - enter for udev rule string SUBSYSTEM=="tty", ATTRS{manufacturer}=="Silicon Labs", ATTRS{
idProduct}=="ea60"
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_impl] parse_udev_rule - parsing udev_rule "SUBSYSTEM==\"tty\", ATTRS{manufacturer}==\"Silicon Labs\", ATTRS{idPr
oduct}==\"ea60\""
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_impl] parse_udev_rule - unsupported field ATTRS{manufacturer}
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_impl] parse_udev_rule - unsupported field ATTRS{idProduct}
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_impl] find_devices - enter with udev_filters [UdevFilter { field: Pair { rule: subsystem, span: Span { str: "SUB
SYSTEM", start: 0, end: 9 }, inner: [] }, operation: equality, value: "tty" }]
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_impl] enumerator_match_udev_filters - enter with udev_filters [UdevFilter { field: Pair { rule: subsystem, span:
Span { str: "SUBSYSTEM", start: 0, end: 9 }, inner: [] }, operation: equality, value: "tty" }]
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_impl] enumerator_nomatch_udev_filters - enter with udev_filters []
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_impl] filter_by_remaining_udev_filters - enter with udev_filters []
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_impl] do_parse_and_find - returning discovered devices with devpaths: ["/dev/ttyAMA0", "/dev/ttyUSB0", "/dev/con
sole", "/dev/ptmx", "/dev/tty", "/dev/tty0", "/dev/tty1", "/dev/tty10", "/dev/tty11", "/dev/tty12", "/dev/tty13", "/dev/tty14", "/dev/tty15", "/dev/tty16", "/dev/tty17", "/de
v/tty18", "/dev/tty19", "/dev/tty2", "/dev/tty20", "/dev/tty21", "/dev/tty22", "/dev/tty23", "/dev/tty24", "/dev/tty25", "/dev/tty26", "/dev/tty27", "/dev/tty28", "/dev/tty29
", "/dev/tty3", "/dev/tty30", "/dev/tty31", "/dev/tty32", "/dev/tty33", "/dev/tty34", "/dev/tty35", "/dev/tty36", "/dev/tty37", "/dev/tty38", "/dev/tty39", "/dev/tty4", "/dev
/tty40", "/dev/tty41", "/dev/tty42", "/dev/tty43", "/dev/tty44", "/dev/tty45", "/dev/tty46", "/dev/tty47", "/dev/tty48", "/dev/tty49", "/dev/tty5", "/dev/tty50", "/dev/tty51"
, "/dev/tty52", "/dev/tty53", "/dev/tty54", "/dev/tty55", "/dev/tty56", "/dev/tty57", "/dev/tty58", "/dev/tty59", "/dev/tty6", "/dev/tty60", "/dev/tty61", "/dev/tty62", "/dev
/tty63", "/dev/tty7", "/dev/tty8", "/dev/tty9", "/dev/ttyprintk"]
[2020-11-08T09:04:14Z TRACE agent::protocols::udev::discovery_handler] discover - mapping and returning devices at devpaths {"/dev/tty41", "/dev/tty24", "/dev/tty20", "/dev/t
ty37", "/dev/tty51", "/dev/tty38", "/dev/tty17", "/dev/tty18", "/dev/tty49", "/dev/tty5", "/dev/tty4", "/dev/tty0", "/dev/tty63", "/dev/tty43", "/dev/tty48", "/dev/tty39", "/
dev/tty46", "/dev/tty28", "/dev/tty11", "/dev/tty54", "/dev/tty36", "/dev/tty30", "/dev/tty52", "/dev/tty16", "/dev/tty2", "/dev/tty45", "/dev/tty61", "/dev/tty25", "/dev/tty
", "/dev/tty59", "/dev/tty42", "/dev/tty29", "/dev/tty47", "/dev/tty56", "/dev/tty55", "/dev/ttyUSB0", "/dev/tty44", "/dev/tty50", "/dev/tty33", "/dev/tty13", "/dev/tty58", "
/dev/tty31", "/dev/ttyAMA0", "/dev/tty6", "/dev/tty10", "/dev/tty8", "/dev/tty35", "/dev/ttyprintk", "/dev/tty32", "/dev/tty14", "/dev/tty60", "/dev/tty23", "/dev/tty27", "/d
ev/tty40", "/dev/tty3", "/dev/tty7", "/dev/ptmx", "/dev/tty1", "/dev/tty19", "/dev/tty15", "/dev/tty53", "/dev/tty62", "/dev/tty22", "/dev/tty9", "/dev/tty21", "/dev/tty26", 
"/dev/tty57", "/dev/tty34", "/dev/console", "/dev/tty12"}
```

### PR DESCRIPTION
**Pull request by kate-goldenring**
**What this PR does / why we need it**:
Previously, the udev discovery handler could only discover devices using the following udev rule fields: `DEVPATH`, `KERNEL`, `TAG`, `DRIVER`, `SUBSYSTEM`, `ATTRIBUTE`, `ENV`. This was limiting, as a lot of properties and attributes are associate with parent devices. Now, you can use udev rules that look up the device hierarchy, expanding the list of total supported rules to: `ATTRIBUTE`, `ATTRIBUTE`, `DEVPATH`, `DRIVER`, `DRIVERS`, `KERNEL`, `KERNELS`, `ENV`, `SUBSYSTEM`, `SUBSYSTEMS`, `TAG`, and `TAGS`.

**Special notes for your reviewer**:
closes #114 

**If applicable**:
- [x] this PR contains documentation
- [x] this PR contains unit tests
- [x] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [x] code is free of common mistakes (`cargo clippy`)
- [x] all Akri tests succeed (`cargo test`)
- [x] inline documentation builds (`cargo doc`)
- [x] version has been updated appropriately (`./version.sh`)

### CODE REVIEW

File: agent/src/protocols/udev/discovery_impl.rs [hunk 1]
```diff
@@ -382,6 +436,126 @@ fn filter_by_remaining_udev_filters(
...
+                device_has_parent_with_subsystem(&parent, subsystem)
+            } else {
+                false
+            }
+        }
+    }
+}
+
+/// Recursively look up a device's hierarchy to see if it has an ancestor with a specified attribute.
+pub fn device_has_parent_with_attribute(
```
Comment (jiria) [inline agent/src/protocols/udev/discovery_impl.rs:466]: Curious why the structure of this function is different from device_has_parent_with_subsystem?

Comment (kate-goldenring) [reply agent/src/protocols/udev/discovery_impl.rs:466]: `device_has_parent_with_subsystem` is different from the other `S` fields because the rust udev library has support for a `parent_with_subsystem` function, while the others don't

**Comment by kate-goldenring** [comment]
After doing some testing making udev rules. It looks like `ATTRS{key}==value` includes the parent that has the `ATTR{key}==value`, as well. Making this change now for all of the `S` fields.

File: agent/src/protocols/udev/discovery_impl.rs [hunk 2]
```diff
@@ -374,6 +370,64 @@ fn filter_by_remaining_udev_filters(
...
+                            device_has_parent_with_sysname(get_parent(device), &value_regex);
+                        (is_equality && is_match) || (!is_equality && !is_match)
+                    })
+                    .collect();
+            }
+            Rule::tags => {
+                mutable_devices = mutable_devices
+                    .into_iter()
+                    .filter(|device| {
+                        let is_match = device_has_parent_with_tag(get_parent(device), &value_regex);
```
Comment (bfjelds) [inline agent/src/protocols/udev/discovery_impl.rs:426]: it feels like there is a lot of *almost* identical code in this file that could be refactored.  i'm not sure if it can be (Rust might make that hard), but some simple things like this could be pulled into a helper method:

```
let is_match = device_has_parent_with_sysname(get_parent(device), &value_regex);
(is_equality && is_match) || (!is_equality && !is_match)
```

Comment (bfjelds) [reply agent/src/protocols/udev/discovery_impl.rs:426]: i wonder if you couldn't use a closure to get even more refactoring ... probably not with Rust:

```
fn filter_udev_prop(is_match: bool) -> bool {
(is_equality && is_match) || (!is_equality && !is_match)
}
fn filter_mutuable_devices(mutable_devices, <closure>) {
  mutable_devices.into_iter().filter(|d| filter_udev_prop(<clusure>(d))).collect()
}
...
            Rule::kernels => {
                mutable_devices = filter_mutuable_devices(mutable_devices, |device| { device_has_parent_with_sysname(get_parent(device), &value_regex) });
            }
```

File: agent/src/protocols/udev/discovery_impl.rs [hunk 3]
```diff
@@ -374,6 +370,64 @@ fn filter_by_remaining_udev_filters(
                     })
                     .collect();
             }
+            Rule::subsystems => {
+                mutable_devices = mutable_devices
+                    .into_iter()
+                    .filter(|device| {
+                        let is_match = device_has_parent_with_subsystem(device, &udev_filter.value);
+                        (is_equality && is_match) || (!is_equality && !is_match)
```
[the remark this answers is not in the document]
Comment (kate-goldenring) [reply agent/src/protocols/udev/discovery_impl.rs:379]: Since I am now checking the device and parent, how does `device_or_parent_has_field` sound?

File: agent/src/protocols/udev/discovery_impl.rs [hunk 4]
```diff
@@ -152,6 +152,7 @@ fn find_devices(
             if let Some(devnode) = get_devnode(&device) {
                 Some(devnode.to_str().unwrap().to_string())
             } else {
+                trace!("find_devices - ignoring device with devpath {:?} due to having no devnode", get_devpath(&device));
```
Comment (kate-goldenring) [inline agent/src/protocols/udev/discovery_impl.rs:155]: Not all devices have devnodes. For instance, the udev rule `SUBSYSTEM=="usb"` finds 9 devpaths on my machine but only 4 of those have devnodes, so while these [testing udev rule](https://github.com/deislabs/akri/blob/main/docs/udev-configuration.md#testing-a-udev-rule) steps show 9 devices, Akri will only create instances for the ones that have devnodes. Should this be changed to using devpath like so:
```
    let device_devpaths: Vec<String> = final_devices
        .into_iter()
        .filter_map(|device| {
            Some(get_devpath(&device).to_str().unwrap().to_string())
        })
        .collect();
```
The udev video broker expects a devnode, so it would need a modification.
It seems that selecting for devnodes makes sense for finding devices, but it is harder to test. I am not quite sure why some items in udev have devpaths but not devnodes. Anyone have an understanding of what qualifies a device for having a devnode vs not?

File: agent/src/protocols/udev/discovery_impl.rs (hunk 2 above)
Comment (kate-goldenring) [reply agent/src/protocols/udev/discovery_impl.rs]: I was thinking about whether i could use closures. It seems the limiting factor is the `impl Trait` `DeviceExt` that is used for testing. For example, 
```
fn filter_mutuable_devices(mutable_devices: Vec<impl DeviceExt>, f: fn(&impl DeviceExt, &Regex) -> bool, arg: &impl DeviceExt, arg2: &Regex) {
...
}
```
Is not possible because "`impl Trait` not allowed outside of function and inherent method return types"

File: agent/src/protocols/udev/discovery_impl.rs (hunk 4 above)
Comment (jiria) [reply agent/src/protocols/udev/discovery_impl.rs]: Curious, are the 9 devices all leaf devices? Are the remaining 5 not exposed under /dev/. but also not under /sys?

File: agent/src/protocols/udev/discovery_impl.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (jiria) [reply agent/src/protocols/udev/discovery_impl.rs:382]: device_or_parents_have_field?

File: agent/src/protocols/udev/discovery_impl.rs (hunk 2 above)
Comment (bfjelds) [reply agent/src/protocols/udev/discovery_impl.rs]: i feared as much.  bummer.

File: agent/src/protocols/udev/discovery_impl.rs (hunk 4 above)
Comment (kate-goldenring) [reply agent/src/protocols/udev/discovery_impl.rs]: They are all exposed under `/sys`. Everything in the Linux Device Filesystem has a syspath; however, not everything has a dev node. For example, all syspaths discovered by `SUBSYSTEM=="usb"`:
/sys/devices/pci0000:00/0000:00:14.0/usb1
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-0:1.0
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/hidraw/hidraw0
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/input/input6
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/input/input6/event3
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/input/input6/input6::capslock
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/input/input6/input6::numlock
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/input/input6/input6::scrolllock
/sys/devices/pci0000:00/0000:00:14.0/usb2
/sys/devices/pci0000:00/0000:00:14.0/usb2/2-0:1.0

However, only the following have devnodes:
/dev/bus/usb/001/001
/dev/bus/usb/001/002
/dev/hidraw0
/dev/input/event3
/dev/bus/usb/002/001

Comment (jiria) [reply agent/src/protocols/udev/discovery_impl.rs]: This is a nice write up: http://reactivated.net/writing_udev_rules.html

Anyways, I think there might be several sources for /dev nodes. 

/etc/udev/rules.d + /lib/udev/rules.d and /usr/lib/rules.d have rules that contain `NAME=` and/or `SYMLINK+=` clauses, which create symlinks  under /dev.

I recall that kernel drivers can also directly create nodes under /dev. Looking at the rules above on my box, I did not see the rules that would explain the dev nodes, so perhaps that is coming out of drivers (though perhaps there is some % substitution in play?).

From the link above, wonder if this would help figure out origin of the 5 devices in /dev:
```
udevtest
If you know the top-level device path in sysfs, you can use udevtest to show the actions which udev would take. This may help you debug your rules. For example, assuming you want to debug a rule which acts on /sys/class/sound/dsp:

# udevtest /class/sound/dsp
main: looking at device '/class/sound/dsp' from subsystem 'sound'
udev_rules_get_name: add symlink 'dsp'
udev_rules_get_name: rule applied, 'dsp' becomes 'sound/dsp'
udev_device_event: device '/class/sound/dsp' already known, remove possible symlinks
udev_node_add: creating device node '/dev/sound/dsp', major = '14', minor = '3', mode = '0660', uid = '0', gid = '18'
udev_node_add: creating symlink '/dev/dsp' to 'sound/dsp'
```
Note the usage is `udevadm test`, not `udevtest`.

In my case:
```
GROUP 104 /lib/udev/rules.d/50-udev-default.rules:29
IMPORT builtin 'hwdb' /lib/udev/rules.d/60-evdev.rules:8
IMPORT builtin 'hwdb' returned non-zero
IMPORT builtin 'hwdb' /lib/udev/rules.d/60-evdev.rules:17
IMPORT builtin 'hwdb' returned non-zero
IMPORT builtin 'hwdb' /lib/udev/rules.d/60-evdev.rules:21
IMPORT builtin 'hwdb' returned non-zero
IMPORT builtin 'input_id' /lib/udev/rules.d/60-input-id.rules:5
capabilities/ev raw kernel attribute: 120013
capabilities/abs raw kernel attribute: 0
capabilities/rel raw kernel attribute: 0
capabilities/key raw kernel attribute: 1000000000007 ff9f207ac14057ff febeffdfffefffff fffffffffffffffe
properties raw kernel attribute: 0
test_key: checking bit block 0 for any keys; found=1
test_key: checking bit block 64 for any keys; found=1
test_key: checking bit block 128 for any keys; found=1
test_key: checking bit block 192 for any keys; found=1
IMPORT builtin 'hwdb' /lib/udev/rules.d/60-input-id.rules:6
IMPORT builtin 'hwdb' returned non-zero
IMPORT builtin 'usb_id' /lib/udev/rules.d/60-persistent-input.rules:11
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0: if_class 3 protocol 0
LINK 'input/by-id/usb-Dell_Dell_USB_Keyboard-event-kbd' /lib/udev/rules.d/60-persistent-input.rules:28
IMPORT builtin 'path_id' /lib/udev/rules.d/60-persistent-input.rules:35
LINK 'input/by-path/pci-0000:00:14.0-usb-0:14:1.0-event-kbd' /lib/udev/rules.d/60-persistent-input.rules:37
PROGRAM 'libinput-device-group /sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/input/input6/event3' /lib/udev/rules.d/80-libinput-device-groups.rules:7
starting 'libinput-device-group /sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/input/input6/event3'
'libinput-device-group /sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/input/input6/event3'(out) '3/413c/2003:usb-0000:00:14.0-14'
Process 'libinput-device-group /sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/input/input6/event3' succeeded.
IMPORT builtin 'hwdb' /lib/udev/rules.d/90-libinput-model-quirks.rules:42
IMPORT builtin 'hwdb' returned non-zero
IMPORT builtin 'hwdb' /lib/udev/rules.d/90-libinput-model-quirks.rules:46
IMPORT builtin 'hwdb' returned non-zero
IMPORT builtin 'hwdb' /lib/udev/rules.d/90-libinput-model-quirks.rules:50
IMPORT builtin 'hwdb' returned non-zero
handling device node '/dev/input/event3', devnum=c13:67, mode=0660, uid=0, gid=104
preserve permissions /dev/input/event3, 020660, uid=0, gid=104
preserve already existing symlink '/dev/char/13:67' to '../input/event3'
found 'c13:67' claiming '/run/udev/links/\x2finput\x2fby-id\x2fusb-Dell_Dell_USB_Keyboard-event-kbd'
creating link '/dev/input/by-id/usb-Dell_Dell_USB_Keyboard-event-kbd' to '/dev/input/event3'
preserve already existing symlink '/dev/input/by-id/usb-Dell_Dell_USB_Keyboard-event-kbd' to '../event3'
found 'c13:67' claiming '/run/udev/links/\x2finput\x2fby-path\x2fpci-0000:00:14.0-usb-0:14:1.0-event-kbd'
creating link '/dev/input/by-path/pci-0000:00:14.0-usb-0:14:1.0-event-kbd' to '/dev/input/event3'
preserve already existing symlink '/dev/input/by-path/pci-0000:00:14.0-usb-0:14:1.0-event-kbd' to '../event3'
.INPUT_CLASS=kbd
.MM_USBIFNUM=00
ACTION=add
BACKSPACE=guess
DEVLINKS=/dev/input/by-id/usb-Dell_Dell_USB_Keyboard-event-kbd /dev/input/by-path/pci-0000:00:14.0-usb-0:14:1.0-event-kbd
DEVNAME=/dev/input/event3
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/0003:413C:2003.0001/input/input6/event3
ID_BUS=usb
ID_INPUT=1
ID_INPUT_KEY=1
ID_INPUT_KEYBOARD=1
ID_MODEL=Dell_USB_Keyboard
ID_MODEL_ENC=Dell\x20USB\x20Keyboard
ID_MODEL_ID=2003
ID_PATH=pci-0000:00:14.0-usb-0:14:1.0
ID_PATH_TAG=pci-0000_00_14_0-usb-0_14_1_0
ID_REVISION=0306
ID_SERIAL=Dell_Dell_USB_Keyboard
ID_TYPE=hid
ID_USB_DRIVER=usbhid
ID_USB_INTERFACES=:030101:
ID_USB_INTERFACE_NUM=00
ID_VENDOR=Dell
ID_VENDOR_ENC=Dell
ID_VENDOR_ID=413c
LIBINPUT_DEVICE_GROUP=3/413c/2003:usb-0000:00:14.0-14
MAJOR=13
MINOR=67
SUBSYSTEM=input
TAGS=:power-switch:akri_tag:
USEC_INITIALIZED=5419248
XKBLAYOUT=us
XKBMODEL=pc105
XKBOPTIONS=
XKBVARIANT=
Unload module index
Unloaded link configuration context.
```
Seems that my case might be your case too based on the presence of the TAG :).

Perhaps this file is responsible? `/lib/udev/rules.d/60-input-id.rules`

Coming back to your original question, would it make sense to craft a rule with more filters, not just `SUBSYSTEM=="usb"`, but perhaps adding a clause for video, or in the example above, input?

Comment (kate-goldenring) [reply agent/src/protocols/udev/discovery_impl.rs]: To clarify: Are you saying that we should use syspath instead of devpath and leave it on the operator to create more specific rules to narrow down the device list? Or that most devices that should be discovered will have devnodes as the drivers for those devices will most likely define rules with NAME= or SYMLINK+= ?

Comment (kate-goldenring) [reply agent/src/protocols/udev/discovery_impl.rs]: Also, I just removed the tag. I am playing with rules in `/etc/udev/rules.d/90-akri.rules`.

Comment (kate-goldenring) [reply agent/src/protocols/udev/discovery_impl.rs]: My hunch is to switch to using `syspath` and modify the udev video broker

Comment (jiria) [reply agent/src/protocols/udev/discovery_impl.rs]: I was not meaning to imply that (I meant to say that either drivers do create the /dev/* nodes or there is udev rule for those). For /dev/input/event3 specifically, there was some udev rule as per the listing above. Also looking specifically under /sys/devices for /dev/input/event3, I do not see a file that could be mounted into container. So I think we need to pick the files from other /dev.

File: docs/udev-configuration.md [hunk 5]
```diff
@@ -41,12 +41,16 @@ To test which devices Akri will discover with a udev rule, you can run the rule
...
-    udevadm control --reload
-    udevadm trigger
+    sudo udevadm control --reload
+    sudo udevadm trigger
     ```
-1. List the devices that have been tagged, which Akri will discover.
+1. List the devices that have been tagged, which Akri will discover. Akri will only discover devices with device nodes (devices within the `/dev` directory). These device node paths will be mounted into broker Pods so the brokers can utilize the devices.
     ```sh
-    udevadm trigger --verbose --dry-run --type=devices --tag-match=akri_tag
+    udevadm trigger --verbose --dry-run --type=devices --tag-match=akri_tag | xargs -l bash -c 'if [ -e $0/dev ]; then echo $0/dev; fi'
```
Comment (jiria) [inline docs/udev-configuration.md:49]: If you have the other ones with sudo, should this one use it too?

**Review by jiria — APPROVED** [review]

File: docs/udev-configuration.md (hunk 5 above)
Comment (kate-goldenring) [reply docs/udev-configuration.md:49]: I think only triggering the rules with `sudo udevadm trigger` required sudo while this one doesnt seem to because of the `--dry-run` part and its read only.

**Review by bfjelds — APPROVED** [review]
